policies:
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.8.0@sha256:fee6562ca456331c519a85b74bf5998169fd8b9754bbea13171f53e06e2e5154
    values:
      - updatecli/values.d/scm.yaml

  - name: Update Helm Charts
    policy: ghcr.io/updatecli/policies/autodiscovery/helm:0.9.0@sha256:74dc40162ccccea441745b443cb5ead90ae4c30f8eb23969935625b069f3a2ff
    values:
      - updatecli/values.d/scm.yaml

  - name: Update GitHub Actions
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.3.0@sha256:3b5425da2a2a2b89bb69463f1294704c33730358c66140efb93cab14b2868b06
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/githubaction.yaml
