apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "udash.configMapName" . }}-server
  labels:
    {{- include "udash.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:

{{- if .Values.readonly }}
  config.yaml: |
    server:
      dryrun: true
    {{- if not .Values.cnpg.enabled }}
    database:
      uri: "{{ .Values.secrets.database.stringdata.uri }}"
    {{- end }}
{{- else }}
  config.yaml: |
    server:
      auth:
        mode: "{{ .Values.secrets.auth.stringdata.mode }}"
        {{- if and ( eq .Values.secrets.auth.stringdata.mode "oauth" ) }}
        issuer: "{{ .Values.secrets.auth.stringdata.issuer }}"
        audience: "{{ .Values.secrets.auth.stringdata.audience }}"
        clientid: "{{ .Values.secrets.auth.stringdata.clientid }}"
        {{- end }}
    {{- if not .Values.cnpg.enabled }}
    database:
      uri: "{{ .Values.secrets.database.stringdata.uri }}"
    {{- end }}
{{- end }}

