apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "udash.configMapName" . }}-server
  labels:
    {{- include "udash.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    server:
      auth:
        mode: "oauth"
        issuer: "{{ .Values.secrets.auth.stringdata.issuer }}"
        audience: "{{ .Values.secrets.auth.stringdata.audience }}"
    database:
      uri: "{{ .Values.secrets.database.stringdata.uri }}"

