{{- if .Values.ingress.enabled -}}
{{- $fullName := include "udash.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- $annotations := .Values.ingress.annotations | deepCopy }}
{{- if and .Values.ingress.traefik.stripPrefix.enabled (ne .Values.ingress.paths.front "/") }}
  {{- $middlewareRef := printf "%s-%s@kubernetescrd" .Release.Namespace (include "udash.traefikStripFrontMiddlewareName" .) }}
  {{- $_ := set $annotations "traefik.ingress.kubernetes.io/router.middlewares" $middlewareRef }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "udash.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.paths.front }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: udash-front
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: udash-front
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- if not $.Values.ingress.server.host }}
          - path: {{ $.Values.ingress.paths.server }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: udash-server
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: udash-server
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- if .Values.ingress.server.host }}
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-server
  labels:
    {{- include "udash.labels" . | nindent 4 }}
  {{- $serverAnnotations := .Values.ingress.server.annotations | deepCopy }}
  {{- if .Values.ingress.traefik.stripPrefix.enabled }}
    {{- $stripRef := printf "%s-%s@kubernetescrd" .Release.Namespace (include "udash.traefikStripServerMiddlewareName" .) }}
    {{- $addRef := printf "%s-%s@kubernetescrd" .Release.Namespace (include "udash.traefikAddServerMiddlewareName" .) }}
    {{- $_ := set $serverAnnotations "traefik.ingress.kubernetes.io/router.middlewares" (printf "%s,%s" $stripRef $addRef) }}
  {{- end }}
  {{- with $serverAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.server.tls }}
  tls:
    {{- range .Values.ingress.server.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.server.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.server.path }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: udash-server
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: udash-server
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
{{- end }}
