{{- if and (include "udash.zitadelKeyEnabled" .) (not .Values.auth.zitadel.keyFile.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "udash.zitadelKeySecretName" . }}
  labels:
    {{- include "udash.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.zitadel.keyFile.key }}: |
    {{- .Values.auth.zitadel.keyFile.content | nindent 4 }}
{{- end }}
