{{- if and .Values.ingress.enabled .Values.ingress.traefik.stripPrefix.enabled (ne .Values.ingress.paths.front "/") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "udash.traefikStripFrontMiddlewareName" . }}
  labels:
    {{- include "udash.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingress.paths.front | quote }}
{{- end }}
