apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "udash.configMapName" . }}-agentrelay
  labels:
    {{- include "udash.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    server:
      auth:
        mode: "none"
    database:
      uri: "{{ .Values.secrets.database.stringdata.uri }}"

