---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "udash.secretName" $ }}'
  labels:
    {{- include "udash.labels" $ | nindent 4 }}
  {{- with $.Values.secrets.agent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $env, $value := $.Values.secrets.agent.environments }}
  {{ $env }}: {{ $value }}
  {{- end }}

