apiVersion: v1
kind: Service
metadata:
  name: agentrelay
  labels:
    {{- include "udash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "udash.selectorLabels.agentrelay" . | nindent 4 }}
