---
name: Updatecli Release
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 12:00 every Thursday
    - cron: "0 12 * * *"
  repository_dispatch:
    types:
      - "updatecli-release"
      - "udash-release"
      - "udash-front-release"
permissions: {}

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          persist-credentials: false

      - name: "Install Updatecli"
        uses: "updatecli/updatecli-action@v2.100.0"
        with:
          version: "v0.114.0"

      - name: "Run updatecli only on release pipelines"
        run: updatecli compose apply --clean-git-branches=true --labels="release:" --experimental
        env:
          UPDATECLI_GITHUB_APP_CLIENT_ID: ${{ secrets.UPDATECLIBOT_APP_ID }}
          UPDATECLI_GITHUB_APP_PRIVATE_KEY: ${{ secrets.UPDATECLIBOT_APP_PRIVKEY }}
          UPDATECLI_GITHUB_APP_INSTALLATION_ID: ${{ secrets.UPDATECLIBOT_APP_INSTALLATION_ID }}
          UPDATECLI_UDASH_API_URL: ${{ secrets.UPDATECLI_UDASH_API_URL }}
          UPDATECLI_UDASH_ACCESS_TOKEN: ${{ secrets.UPDATECLI_UDASH_ACCESS_TOKEN }}
          UPDATECLI_UDASH_URL: ${{ secrets.UPDATECLI_UDASH_URL }}
