name: updatecli
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every hour
    - cron: '0 * * * *'
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2"
      - name: "Run updatecli in dryrun"
        run: "updatecli compose diff"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: generate_token
        if: github.ref == 'refs/heads/main'
        with:
          app-id: ${{ secrets.UPDATECLIBOT_APP_ID }}
          private-key: ${{ secrets.UPDATECLIBOT_APP_PRIVKEY }}
      - name: "Run updatecli"
        if: github.ref == 'refs/heads/main'
        run: "updatecli compose apply"
        env:
          GITHUB_ACTOR: ${{ secrets.UPDATECLI_BOT_GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
